package net.multicom.WSTestes;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 08-12-2015
//
//---------------------------------------------------



import org.ksoap2.serialization.*;
import java.util.Vector;
import java.util.Hashtable;


public class OWBArrayOfProduto extends Vector< OWBProduto_1> implements KvmSerializable
{
    
    public OWBArrayOfProduto(){}
    
    public OWBArrayOfProduto(java.lang.Object inObj,OWBExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        SoapObject soapObject=(SoapObject)inObj;
        int size = soapObject.getPropertyCount();
        for (int i0=0;i0< size;i0++)
        {
            java.lang.Object obj = soapObject.getProperty(i0);
            if (obj!=null && obj instanceof AttributeContainer)
            {
                AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                OWBProduto_1 j1= (OWBProduto_1)__envelope.get(j,OWBProduto_1.class);
                add(j1);
            }
        }
}
    
    @Override
    public java.lang.Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "Produto";
        info.type = OWBProduto_1.class;
    	info.namespace= "http://schemas.datacontract.org/2004/07/MultiPagos.PDVController.Contracts";
    }


    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }

}