package net.multicom.WSTestes;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 08-12-2015
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;
import java.util.Vector;


public class OWBArrayOfOperadora extends Vector<net.multicom.WSTestes.OWBOperadora_1> implements KvmSerializable
{
    
    public OWBArrayOfOperadora(){}
    
    public OWBArrayOfOperadora(java.lang.Object inObj, net.multicom.WSTestes.OWBExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        SoapObject soapObject=(SoapObject)inObj;
        int size = soapObject.getPropertyCount();
        for (int i0=0;i0< size;i0++)
        {
            java.lang.Object obj = soapObject.getProperty(i0);
            if (obj!=null && obj instanceof AttributeContainer)
            {
                AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                net.multicom.WSTestes.OWBOperadora_1 j1= (net.multicom.WSTestes.OWBOperadora_1)__envelope.get(j, net.multicom.WSTestes.OWBOperadora_1.class);
                add(j1);
            }
        }
}
    
    @Override
    public java.lang.Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "Operadora";
        info.type = net.multicom.WSTestes.OWBOperadora_1.class;
    	info.namespace= "http://schemas.datacontract.org/2004/07/MultiPagos.PDVController.Contracts";
    }


    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }

}