package net.multicom.WSTestes;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 08-12-2015
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.math.BigDecimal;
import java.util.Hashtable;
import java.util.UUID;

public class OWBCartaoRecarga extends AttributeContainer implements KvmSerializable
{

    
    public UUID _x005F_x003C_CartaoRecargaId_x005F_x003E_k__BackingField=OWBHelper.emptyGuid();
    
    public String _x005F_x003C_CodigoCompraFornecedor_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_CodigoDeBarras_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_CodigoInformado_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_CodigoProduto_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_DDD_x005F_x003E_k__BackingField;
    
    public java.util.Date _x005F_x003C_DataCriacao_x005F_x003E_k__BackingField;
    
    public java.util.Date _x005F_x003C_DataModificacao_x005F_x003E_k__BackingField;
    
    public java.util.Date _x005F_x003C_DataVencimento_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_Descricao_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_FornecedorId_x005F_x003E_k__BackingField=0;
    
    public String _x005F_x003C_Lote_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_MensagemOperadora_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_ModeloId_x005F_x003E_k__BackingField=0;
    
    public String _x005F_x003C_NomeOperadora_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_NomeProduto_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_NsuFornecedor_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_OrigemId_x005F_x003E_k__BackingField=0;
    
    public String _x005F_x003C_PIN_x005F_x003E_k__BackingField;
    
    public UUID _x005F_x003C_PagamentoId_x005F_x003E_k__BackingField;
    
    public OWBPagamento _x005F_x003C_Pagamento_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_PosId_x005F_x003E_k__BackingField=0;
    
    public Boolean _x005F_x003C_RecursoReservado_x005F_x003E_k__BackingField=false;
    
    public String _x005F_x003C_Serie_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_StatusId_x005F_x003E_k__BackingField=0;
    
    public Integer _x005F_x003C_StatusImpressaoId_x005F_x003E_k__BackingField=0;
    
    public String _x005F_x003C_Telefone_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_Validade_x005F_x003E_k__BackingField=0;
    
    public BigDecimal _x005F_x003C_Valor_x005F_x003E_k__BackingField=BigDecimal.ZERO;

    public OWBCartaoRecarga ()
    {
    }

    public OWBCartaoRecarga (java.lang.Object paramObj,OWBExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("_x003C_CartaoRecargaId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_CartaoRecargaId_x005F_x003E_k__BackingField = UUID.fromString(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof UUID){
                        this._x005F_x003C_CartaoRecargaId_x005F_x003E_k__BackingField = (UUID)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_CodigoCompraFornecedor_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_CodigoCompraFornecedor_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_CodigoCompraFornecedor_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_CodigoDeBarras_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_CodigoDeBarras_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_CodigoDeBarras_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_CodigoInformado_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_CodigoInformado_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_CodigoInformado_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_CodigoOperadora_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_CodigoProduto_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_CodigoProduto_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_CodigoProduto_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_DDD_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_DDD_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_DDD_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_DataCriacao_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_DataCriacao_x005F_x003E_k__BackingField = OWBHelper.ConvertFromWebService(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof java.util.Date){
                        this._x005F_x003C_DataCriacao_x005F_x003E_k__BackingField = (java.util.Date)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_DataModificacao_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_DataModificacao_x005F_x003E_k__BackingField = OWBHelper.ConvertFromWebService(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof java.util.Date){
                        this._x005F_x003C_DataModificacao_x005F_x003E_k__BackingField = (java.util.Date)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_DataVencimento_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_DataVencimento_x005F_x003E_k__BackingField = OWBHelper.ConvertFromWebService(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof java.util.Date){
                        this._x005F_x003C_DataVencimento_x005F_x003E_k__BackingField = (java.util.Date)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Descricao_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Descricao_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_Descricao_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_FornecedorId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_FornecedorId_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_FornecedorId_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Lote_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Lote_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_Lote_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_MensagemOperadora_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_MensagemOperadora_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_MensagemOperadora_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ModeloId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ModeloId_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_ModeloId_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_NomeOperadora_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_NomeOperadora_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_NomeOperadora_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_NomeProduto_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_NomeProduto_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_NomeProduto_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_NsuFornecedor_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_NsuFornecedor_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_NsuFornecedor_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_OrigemId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_OrigemId_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_OrigemId_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_PIN_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_PIN_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_PIN_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_PagamentoId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_PagamentoId_x005F_x003E_k__BackingField = UUID.fromString(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof UUID){
                        this._x005F_x003C_PagamentoId_x005F_x003E_k__BackingField = (UUID)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Pagamento_x003E_k__BackingField"))
                {
                    java.lang.Object j = obj;
                    this._x005F_x003C_Pagamento_x005F_x003E_k__BackingField = (OWBPagamento)__envelope.get(j,OWBPagamento.class);
                    continue;
                }
                if (info.name.equals("_x003C_PosId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_PosId_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_PosId_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_RecursoReservado_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_RecursoReservado_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_RecursoReservado_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Serie_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Serie_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_Serie_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_StatusId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_StatusId_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_StatusId_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_StatusImpressaoId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_StatusImpressaoId_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_StatusImpressaoId_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Telefone_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Telefone_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_Telefone_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Validade_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Validade_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_Validade_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Valor_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Valor_x005F_x003E_k__BackingField = new BigDecimal(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof BigDecimal){
                        this._x005F_x003C_Valor_x005F_x003E_k__BackingField = (BigDecimal)obj;
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return _x005F_x003C_CartaoRecargaId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==1)
        {
            return this._x005F_x003C_CodigoCompraFornecedor_x005F_x003E_k__BackingField!=null?this._x005F_x003C_CodigoCompraFornecedor_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==2)
        {
            return this._x005F_x003C_CodigoDeBarras_x005F_x003E_k__BackingField!=null?this._x005F_x003C_CodigoDeBarras_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==3)
        {
            return this._x005F_x003C_CodigoInformado_x005F_x003E_k__BackingField!=null?this._x005F_x003C_CodigoInformado_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==4)
        {
            return this._x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField!=null?this._x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==5)
        {
            return this._x005F_x003C_CodigoProduto_x005F_x003E_k__BackingField!=null?this._x005F_x003C_CodigoProduto_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==6)
        {
            return this._x005F_x003C_DDD_x005F_x003E_k__BackingField!=null?this._x005F_x003C_DDD_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==7)
        {
            return this._x005F_x003C_DataCriacao_x005F_x003E_k__BackingField!=null?OWBHelper.getDateTimeFormat().format(this._x005F_x003C_DataCriacao_x005F_x003E_k__BackingField):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this._x005F_x003C_DataModificacao_x005F_x003E_k__BackingField!=null?OWBHelper.getDateTimeFormat().format(this._x005F_x003C_DataModificacao_x005F_x003E_k__BackingField):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this._x005F_x003C_DataVencimento_x005F_x003E_k__BackingField!=null?OWBHelper.getDateTimeFormat().format(this._x005F_x003C_DataVencimento_x005F_x003E_k__BackingField):SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==10)
        {
            return this._x005F_x003C_Descricao_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Descricao_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==11)
        {
            return _x005F_x003C_FornecedorId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==12)
        {
            return this._x005F_x003C_Lote_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Lote_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==13)
        {
            return this._x005F_x003C_MensagemOperadora_x005F_x003E_k__BackingField!=null?this._x005F_x003C_MensagemOperadora_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==14)
        {
            return _x005F_x003C_ModeloId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==15)
        {
            return this._x005F_x003C_NomeOperadora_x005F_x003E_k__BackingField!=null?this._x005F_x003C_NomeOperadora_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==16)
        {
            return this._x005F_x003C_NomeProduto_x005F_x003E_k__BackingField!=null?this._x005F_x003C_NomeProduto_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==17)
        {
            return this._x005F_x003C_NsuFornecedor_x005F_x003E_k__BackingField!=null?this._x005F_x003C_NsuFornecedor_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==18)
        {
            return _x005F_x003C_OrigemId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==19)
        {
            return this._x005F_x003C_PIN_x005F_x003E_k__BackingField!=null?this._x005F_x003C_PIN_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==20)
        {
            return this._x005F_x003C_PagamentoId_x005F_x003E_k__BackingField!=null?this._x005F_x003C_PagamentoId_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==21)
        {
            return this._x005F_x003C_Pagamento_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Pagamento_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==22)
        {
            return _x005F_x003C_PosId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==23)
        {
            return _x005F_x003C_RecursoReservado_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==24)
        {
            return this._x005F_x003C_Serie_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Serie_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==25)
        {
            return _x005F_x003C_StatusId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==26)
        {
            return _x005F_x003C_StatusImpressaoId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==27)
        {
            return this._x005F_x003C_Telefone_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Telefone_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==28)
        {
            return _x005F_x003C_Validade_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==29)
        {
            return this._x005F_x003C_Valor_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Valor_x005F_x003E_k__BackingField.toString():SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 30;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_CartaoRecargaId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_CodigoCompraFornecedor_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_CodigoDeBarras_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_CodigoInformado_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_CodigoOperadora_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_CodigoProduto_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_DDD_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_DataCriacao_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_DataModificacao_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_DataVencimento_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Descricao_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_FornecedorId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Lote_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_MensagemOperadora_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_ModeloId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_NomeOperadora_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_NomeProduto_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_NsuFornecedor_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_OrigemId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_PIN_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_PagamentoId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==21)
        {
            info.type = OWBPagamento.class;
            info.name = "_x003C_Pagamento_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_PosId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_RecursoReservado_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Serie_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_StatusId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_StatusImpressaoId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Telefone_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_Validade_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Valor_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
    }


    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
