package net.multicom.WSTestes;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 08-12-2015
//
//---------------------------------------------------



import java.util.EnumSet;
import java.util.Set;


public class OWBEnums
{

    public enum EmpresasContaSemFatura
    {
        
        Nenhuma(0),
        
        Elektro(1),
        
        NET(2);
        
        private int code;
        
        EmpresasContaSemFatura(int code ){
            this.code = code;
        }
    
        public int getCode(){
		    return code;
	    }
    

        public static EmpresasContaSemFatura fromString(String str)
        {
            if (str.equals("Nenhuma"))
                return Nenhuma;
            if (str.equals("Elektro"))
                return Elektro;
            if (str.equals("NET"))
                return NET;
		    return null;
        }
        public static EnumSet<EmpresasContaSemFatura> getStatusFlags(String strValue)
        {
            String[] values=strValue.split("\\s+");
            
            EnumSet statusFlags = EnumSet.noneOf(EmpresasContaSemFatura.class);
            for(String val : values)
            {
                EmpresasContaSemFatura enumValue=EmpresasContaSemFatura.fromString(val);
                if(!enumValue.equals(EmpresasContaSemFatura.Nenhuma))
                {
                    statusFlags.add(enumValue) ;
                }
            }
            return statusFlags;
        } 
        
        public static String getFlagValue(Set<EmpresasContaSemFatura> flags)
        {
            String value="";
            for(EmpresasContaSemFatura val :flags)
            {
                value+=val.toString()+" ";
            }
            if(OWBHelper.isEmpty(value))
            {
                value=EmpresasContaSemFatura.Nenhuma.toString();
            }
            return value;
        }
    }

    public enum ModulosPDV
    {
        
        Nenhum(0),
        
        Pagamento(1),
        
        ContaSemFatura(2),
        
        Recarga(4),
        
        ReImpressao(8);
        
        private int code;
        
        ModulosPDV(int code ){
            this.code = code;
        }
    
        public int getCode(){
		    return code;
	    }
    

        public static ModulosPDV fromString(String str)
        {
            if (str.equals("Nenhum"))
                return Nenhum;
            if (str.equals("Pagamento"))
                return Pagamento;
            if (str.equals("ContaSemFatura"))
                return ContaSemFatura;
            if (str.equals("Recarga"))
                return Recarga;
            if (str.equals("ReImpressao"))
                return ReImpressao;
		    return null;
        }
        public static EnumSet<ModulosPDV> getStatusFlags(String strValue)
        {
            String[] values=strValue.split("\\s+");
            
            EnumSet statusFlags = EnumSet.noneOf(ModulosPDV.class);
            for(String val : values)
            {
                ModulosPDV enumValue=ModulosPDV.fromString(val);
                if(!enumValue.equals(ModulosPDV.Nenhum))
                {
                    statusFlags.add(enumValue) ;
                }
            }
            return statusFlags;
        } 
        
        public static String getFlagValue(Set<ModulosPDV> flags)
        {
            String value="";
            for(ModulosPDV val :flags)
            {
                value+=val.toString()+" ";
            }
            if(OWBHelper.isEmpty(value))
            {
                value=ModulosPDV.Nenhum.toString();
            }
            return value;
        }
    }

    public enum FormaPagamento
    {
        
        NaoDefinido(0),
        
        TEF(1),
        
        Cheque(2),
        
        Dinheiro(3);
        
        private int code;
        
        FormaPagamento(int code ){
            this.code = code;
        }
    
        public int getCode(){
		    return code;
	    }
    

        public static FormaPagamento fromString(String str)
        {
            if (str.equals("NaoDefinido"))
                return NaoDefinido;
            if (str.equals("TEF"))
                return TEF;
            if (str.equals("Cheque"))
                return Cheque;
            if (str.equals("Dinheiro"))
                return Dinheiro;
		    return null;
        }
    }

    public enum StatusImpressao
    {
        
        NaoDefinido(0),
        
        ImpressoOk(10),
        
        ReImpresso(20),
        
        FalhaImpressao(-10);
        
        private int code;
        
        StatusImpressao(int code ){
            this.code = code;
        }
    
        public int getCode(){
		    return code;
	    }
    

        public static StatusImpressao fromString(String str)
        {
            if (str.equals("NaoDefinido"))
                return NaoDefinido;
            if (str.equals("ImpressoOk"))
                return ImpressoOk;
            if (str.equals("ReImpresso"))
                return ReImpresso;
            if (str.equals("FalhaImpressao"))
                return FalhaImpressao;
		    return null;
        }
    }

}