package net.multicom.WSTestes;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 08-12-2015
//
//---------------------------------------------------



public interface OWBIServiceEvents
{
    public void Starting();
    public void Completed(OWBOperationResult result);
}
