package net.multicom.WSTestes;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 08-12-2015
//
//---------------------------------------------------


import android.util.Log;

import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.HttpsTransportSE;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;


public class OWBMultiPagosHomolog
{
    interface OWBIWcfMethod
    {
        OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://homolog-wspdvmultipagos.azurewebsites.net/PontoDeVendaService.svc";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    OWBIServiceEvents callback;
    public OWBMultiPagosHomolog(){}

    public OWBMultiPagosHomolog (OWBIServiceEvents callback)
    {
        this.callback = callback;
    }
    public OWBMultiPagosHomolog(OWBIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public OWBMultiPagosHomolog(OWBIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;

    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected OWBExtendedSoapSerializationEnvelope createEnvelope()
    {
        OWBExtendedSoapSerializationEnvelope envelope= new OWBExtendedSoapSerializationEnvelope(OWBExtendedSoapSerializationEnvelope.VER12);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,OWBExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,OWBExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public OWBPointOfSaleConfig_1 ObterConfiguracao(final Integer posID,final UUID terminalId,final String versao ) throws java.lang.Exception
    {
        return (OWBPointOfSaleConfig_1)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "ObterConfiguracao");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="posID";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(posID!=null?posID:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="terminalId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(terminalId!=null?terminalId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="versao";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(versao!=null?versao:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (OWBPointOfSaleConfig_1)getResult(OWBPointOfSaleConfig_1.class,__result,"ObterConfiguracaoResult",__envelope);
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/ObterConfiguracao");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< OWBPointOfSaleConfig_1>> ObterConfiguracaoAsync(final Integer posID,final UUID terminalId,final String versao)
    {
        return executeAsync(new OWBFunctions.IFunc< OWBPointOfSaleConfig_1>() {
            public OWBPointOfSaleConfig_1 Func() throws java.lang.Exception {
                return ObterConfiguracao( posID,terminalId,versao);
            }
        });
    }
    
    public String SolicitarAutorizacao(final String buffDoc ) throws java.lang.Exception
    {
        return (String)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "SolicitarAutorizacao");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="buffDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(buffDoc!=null?buffDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("SolicitarAutorizacaoResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/SolicitarAutorizacao");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> SolicitarAutorizacaoAsync(final String buffDoc)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return SolicitarAutorizacao( buffDoc);
            }
        });
    }
    
    public void RejeitarDocumento(final String buffDoc,final String motivo ) throws java.lang.Exception
    {
        execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "RejeitarDocumento");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="buffDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(buffDoc!=null?buffDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="motivo";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(motivo!=null?motivo:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/RejeitarDocumento");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> RejeitarDocumentoAsync(final String buffDoc,final String motivo)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RejeitarDocumento( buffDoc,motivo);
                return null;
            }
        }) ;
    }
    
    public String EscolherFormaPagamento(final String buffDoc,final OWBEnums.FormaPagamento forma ) throws java.lang.Exception
    {
        return (String)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "EscolherFormaPagamento");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="buffDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(buffDoc!=null?buffDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="forma";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(forma!=null?forma.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("EscolherFormaPagamentoResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/EscolherFormaPagamento");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> EscolherFormaPagamentoAsync(final String buffDoc,final OWBEnums.FormaPagamento forma)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return EscolherFormaPagamento( buffDoc,forma);
            }
        });
    }
    
    public String EfetivarPagamento(final String buffDoc ) throws java.lang.Exception
    {
        return (String)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "EfetivarPagamento");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="buffDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(buffDoc!=null?buffDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("EfetivarPagamentoResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/EfetivarPagamento");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> EfetivarPagamentoAsync(final String buffDoc)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return EfetivarPagamento( buffDoc);
            }
        });
    }
    
    public void RegistrarProblemaPagamento(final String buffDoc,final String textoInformativo ) throws java.lang.Exception
    {
        execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "RegistrarProblemaPagamento");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="buffDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(buffDoc!=null?buffDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="textoInformativo";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(textoInformativo!=null?textoInformativo:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/RegistrarProblemaPagamento");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> RegistrarProblemaPagamentoAsync(final String buffDoc,final String textoInformativo)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RegistrarProblemaPagamento( buffDoc,textoInformativo);
                return null;
            }
        }) ;
    }
    
    public void RegistrarCancelamentoPagamento(final String buffDoc,final String textoInformativo ) throws java.lang.Exception
    {
        execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "RegistrarCancelamentoPagamento");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="buffDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(buffDoc!=null?buffDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="textoInformativo";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(textoInformativo!=null?textoInformativo:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/RegistrarCancelamentoPagamento");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> RegistrarCancelamentoPagamentoAsync(final String buffDoc,final String textoInformativo)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RegistrarCancelamentoPagamento( buffDoc,textoInformativo);
                return null;
            }
        }) ;
    }
    
    public void RegistrarNovaTentativaPagamento(final String buffDoc ) throws java.lang.Exception
    {
        execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "RegistrarNovaTentativaPagamento");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="buffDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(buffDoc!=null?buffDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/RegistrarNovaTentativaPagamento");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> RegistrarNovaTentativaPagamentoAsync(final String buffDoc)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RegistrarNovaTentativaPagamento( buffDoc);
                return null;
            }
        }) ;
    }
    
    public void RegistraImpressao(final Integer posId,final String buffDoc,final OWBEnums.StatusImpressao statusImpressao,final Integer quantidadeLinhas ) throws java.lang.Exception
    {
        execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "RegistraImpressao");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="posId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(posId!=null?posId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="buffDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(buffDoc!=null?buffDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="statusImpressao";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(statusImpressao!=null?statusImpressao.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="quantidadeLinhas";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(quantidadeLinhas!=null?quantidadeLinhas:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/RegistraImpressao");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> RegistraImpressaoAsync(final Integer posId,final String buffDoc,final OWBEnums.StatusImpressao statusImpressao,final Integer quantidadeLinhas)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RegistraImpressao( posId,buffDoc,statusImpressao,quantidadeLinhas);
                return null;
            }
        }) ;
    }
    
    public String ReimpressaoCodigoBarras(final String codigoBarras ) throws java.lang.Exception
    {
        return (String)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "ReimpressaoCodigoBarras");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="codigoBarras";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(codigoBarras!=null?codigoBarras:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("ReimpressaoCodigoBarrasResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/ReimpressaoCodigoBarras");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> ReimpressaoCodigoBarrasAsync(final String codigoBarras)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ReimpressaoCodigoBarras( codigoBarras);
            }
        });
    }
    
    public String ReimpressaoAutenticacao(final String autenticacao ) throws java.lang.Exception
    {
        return (String)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "ReimpressaoAutenticacao");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="autenticacao";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(autenticacao!=null?autenticacao:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("ReimpressaoAutenticacaoResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/ReimpressaoAutenticacao");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> ReimpressaoAutenticacaoAsync(final String autenticacao)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ReimpressaoAutenticacao( autenticacao);
            }
        });
    }
    
    public OWBCartaoRecarga_1 ReimpressaoCartaoRecarga(final String ddd,final String telefone ) throws java.lang.Exception
    {
        return (OWBCartaoRecarga_1)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "ReimpressaoCartaoRecarga");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="ddd";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ddd!=null?ddd:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="telefone";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(telefone!=null?telefone:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (OWBCartaoRecarga_1)getResult(OWBCartaoRecarga_1.class,__result,"ReimpressaoCartaoRecargaResult",__envelope);
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/ReimpressaoCartaoRecarga");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< OWBCartaoRecarga_1>> ReimpressaoCartaoRecargaAsync(final String ddd,final String telefone)
    {
        return executeAsync(new OWBFunctions.IFunc< OWBCartaoRecarga_1>() {
            public OWBCartaoRecarga_1 Func() throws java.lang.Exception {
                return ReimpressaoCartaoRecarga( ddd,telefone);
            }
        });
    }
    
    public OWBArrayOfOperadora ObterOperadoras(final Integer posId ) throws java.lang.Exception
    {
        return (OWBArrayOfOperadora)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "ObterOperadoras");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="posId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(posId!=null?posId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                Log.i("result__",__result.toString());
                return (OWBArrayOfOperadora)getResult(OWBArrayOfOperadora.class,__result,"ObterOperadorasResult",__envelope);
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/ObterOperadoras");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< OWBArrayOfOperadora>> ObterOperadorasAsync(final Integer posId)
    {
        return executeAsync(new OWBFunctions.IFunc< OWBArrayOfOperadora>() {
            public OWBArrayOfOperadora Func() throws java.lang.Exception {
                return ObterOperadoras( posId);
            }
        });
    }
    
    public OWBArrayOfProduto ObterProdutos(final Integer posId,final OWBOperadora_1 operadora ) throws java.lang.Exception
    {
        return (OWBArrayOfProduto)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://www.ccsdiscovery.com.br/MultiPagos/","operadora",new OWBOperadora_1().getClass());
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "ObterProdutos");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="posId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(posId!=null?posId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="operadora";
                __info.type=OWBOperadora_1.class;
                __info.setValue(operadora!=null?operadora:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (OWBArrayOfProduto)getResult(OWBArrayOfProduto.class,__result,"ObterProdutosResult",__envelope);
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/ObterProdutos");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< OWBArrayOfProduto>> ObterProdutosAsync(final Integer posId,final OWBOperadora_1 operadora)
    {
        return executeAsync(new OWBFunctions.IFunc< OWBArrayOfProduto>() {
            public OWBArrayOfProduto Func() throws java.lang.Exception {
                return ObterProdutos( posId,operadora);
            }
        });
    }
    
    public OWBCartaoRecarga_1 CriarCartaoRecarga(final Integer posId,final OWBProduto_1 produto,final BigDecimal valor,final String ddd,final String telefone ) throws java.lang.Exception
    {
        return (OWBCartaoRecarga_1)execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://www.ccsdiscovery.com.br/MultiPagos/","produto",new OWBProduto_1().getClass());
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "CriarCartaoRecarga");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="posId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(posId!=null?posId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="produto";
                __info.type=OWBProduto_1.class;
                __info.setValue(produto!=null?produto:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="valor";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(valor!=null?valor.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="ddd";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ddd!=null?ddd:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="telefone";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(telefone!=null?telefone:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (OWBCartaoRecarga_1)getResult(OWBCartaoRecarga_1.class,__result,"CriarCartaoRecargaResult",__envelope);
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/CriarCartaoRecarga");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< OWBCartaoRecarga_1>> CriarCartaoRecargaAsync(final Integer posId,final OWBProduto_1 produto,final BigDecimal valor,final String ddd,final String telefone)
    {
        return executeAsync(new OWBFunctions.IFunc< OWBCartaoRecarga_1>() {
            public OWBCartaoRecarga_1 Func() throws java.lang.Exception {
                return CriarCartaoRecarga( posId,produto,valor,ddd,telefone);
            }
        });
    }
    
    public void RejeitarCartaoRecarga(final OWBCartaoRecarga_1 cartao ) throws java.lang.Exception
    {
        execute(new OWBIWcfMethod()
        {
            @Override
            public OWBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              OWBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://www.ccsdiscovery.com.br/MultiPagos/","cartao",new OWBCartaoRecarga_1().getClass());
                SoapObject __soapReq = new SoapObject("http://www.ccsdiscovery.com.br/MultiPagos/", "RejeitarCartaoRecarga");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.ccsdiscovery.com.br/MultiPagos/";
                __info.name="cartao";
                __info.type=OWBCartaoRecarga_1.class;
                __info.setValue(cartao!=null?cartao:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OWBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://www.ccsdiscovery.com.br/MultiPagos/IPontoDeVenda/RejeitarCartaoRecarga");
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> RejeitarCartaoRecargaAsync(final OWBCartaoRecarga_1 cartao)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RejeitarCartaoRecarga( cartao);
                return null;
            }
        }) ;
    }
    
    public void CancelarCartaoRecarga(final String cartao ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> CancelarCartaoRecargaAsync(final String cartao)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                CancelarCartaoRecarga( cartao);
                return null;
            }
        }) ;
    }
    
    public String IniciarPagamentoRecarga(final String cartao ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> IniciarPagamentoRecargaAsync(final String cartao)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return IniciarPagamentoRecarga( cartao);
            }
        });
    }
    
    public void RegistrarProblemaPagamentoRecarga(final String documento,final String textoInformativo ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> RegistrarProblemaPagamentoRecargaAsync(final String documento,final String textoInformativo)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RegistrarProblemaPagamentoRecarga( documento,textoInformativo);
                return null;
            }
        }) ;
    }
    
    public void RegistrarNovaTentativaPagamentoRecarga(final String documento ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> RegistrarNovaTentativaPagamentoRecargaAsync(final String documento)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RegistrarNovaTentativaPagamentoRecarga( documento);
                return null;
            }
        }) ;
    }
    
    public void RegistrarCancelamentoPagamentoRecarga(final String documento,final String textoInformativo ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> RegistrarCancelamentoPagamentoRecargaAsync(final String documento,final String textoInformativo)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                RegistrarCancelamentoPagamentoRecarga( documento,textoInformativo);
                return null;
            }
        }) ;
    }
    
    public String EfetivarPagamentoRecarga(final String documento ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> EfetivarPagamentoRecargaAsync(final String documento)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return EfetivarPagamentoRecarga( documento);
            }
        });
    }
    
    public String RegistraTerminalPdv(final String posId ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> RegistraTerminalPdvAsync(final String posId)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return RegistraTerminalPdv( posId);
            }
        });
    }
    
    public String ObterPdvId(final String machineId ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> ObterPdvIdAsync(final String machineId)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ObterPdvId( machineId);
            }
        });
    }
    
    public String OnlineNotification(final String posID ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> OnlineNotificationAsync(final String posID)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return OnlineNotification( posID);
            }
        });
    }
    
    public String VerificarDisponibilidadePDV(final String posId ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> VerificarDisponibilidadePDVAsync(final String posId)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return VerificarDisponibilidadePDV( posId);
            }
        });
    }
    
    public String ObterImagemPDV(final String posId ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> ObterImagemPDVAsync(final String posId)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ObterImagemPDV( posId);
            }
        });
    }
    
    public void TransmitirLogs(final String pdvId,final String logsCompactados ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< Void>> TransmitirLogsAsync(final String pdvId,final String logsCompactados)
    {
        return executeAsync(new OWBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                TransmitirLogs( pdvId,logsCompactados);
                return null;
            }
        }) ;
    }
    
    public String EnviarComprovantePagamentoViaSms(final String posId,final String autenticacao,final String ddd,final String telefone ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> EnviarComprovantePagamentoViaSmsAsync(final String posId,final String autenticacao,final String ddd,final String telefone)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return EnviarComprovantePagamentoViaSms( posId,autenticacao,ddd,telefone);
            }
        });
    }
    
    public String RealizarConsulta(final String empresaId,final String identificacaoCliente ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> RealizarConsultaAsync(final String empresaId,final String identificacaoCliente)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return RealizarConsulta( empresaId,identificacaoCliente);
            }
        });
    }
    
    public String AutorizarPendencia(final String pendencia,final String identificacao,final String posId ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, OWBOperationResult< String>> AutorizarPendenciaAsync(final String pendencia,final String identificacao,final String posId)
    {
        return executeAsync(new OWBFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return AutorizarPendencia( pendencia,identificacao,posId);
            }
        });
    }

    
    protected java.lang.Object execute(OWBIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        OWBExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, OWBOperationResult< T>>  executeAsync(final OWBFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, OWBOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected OWBOperationResult< T> doInBackground(Void... params) {
                OWBOperationResult< T> result = new OWBOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(OWBOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,OWBExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }
}


