package net.multicom.WSTestes;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 08-12-2015
//
//---------------------------------------------------


import net.multicom.WSTestes.OWBEnums;
import net.multicom.WSTestes.OWBExtendedSoapSerializationEnvelope;
import net.multicom.WSTestes.OWBHelper;

import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.EnumSet;
import java.util.Hashtable;
import java.util.UUID;

public abstract class OWBPointOfSaleConfig extends AttributeContainer implements KvmSerializable
{

    
    public String _x005F_x003C_CabecalhoComprovante_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_ClientTefId_x005F_x003E_k__BackingField=0;
    
    public Boolean _x005F_x003C_ColetarLogs_x005F_x003E_k__BackingField=false;
    
    public EnumSet<OWBEnums.EmpresasContaSemFatura> _x005F_x003C_EmpresasContasSemFatura_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_Estado_x005F_x003E_k__BackingField;
    
    public Boolean _x005F_x003C_ExibirBotaoFechar_x005F_x003E_k__BackingField=false;
    
    public String _x005F_x003C_FormatoData_x005F_x003E_k__BackingField;
    
    public Boolean _x005F_x003C_ImportarArquivos_x005F_x003E_k__BackingField=false;
    
    public String _x005F_x003C_IpClient_x005F_x003E_k__BackingField;
    
    public java.util.Date _x005F_x003C_LastOnlineNotification_x005F_x003E_k__BackingField;
    
    public Boolean _x005F_x003C_LimparLogs_x005F_x003E_k__BackingField=false;
    
    public Boolean _x005F_x003C_LogDetalhado_x005F_x003E_k__BackingField=false;
    
    public String _x005F_x003C_LogoClienteContentType_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_LogoCliente_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_MaxNotificationInterval_x005F_x003E_k__BackingField=0;
    
    public String _x005F_x003C_MensagemCabecalho_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_MensagemIndisponivel_x005F_x003E_k__BackingField;
    
    public EnumSet<OWBEnums.ModulosPDV> _x005F_x003C_Modulos_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_MultipagosPath_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_Nome_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_NotificationInterval_x005F_x003E_k__BackingField=0;
    
    public Integer _x005F_x003C_PointOfSaleID_x005F_x003E_k__BackingField=0;
    
    public Integer _x005F_x003C_PointOfSaleIdParceiro_x005F_x003E_k__BackingField;
    
    public Boolean _x005F_x003C_ReiniciarPrograma_x005F_x003E_k__BackingField=false;
    
    public String _x005F_x003C_RodapeComprovante_x005F_x003E_k__BackingField;
    
    public Boolean _x005F_x003C_StatusServicoPDV_x005F_x003E_k__BackingField=false;
    
    public String _x005F_x003C_TefRequestPath_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_TefResponsePath_x005F_x003E_k__BackingField;
    
    public UUID _x005F_x003C_TerminalId_x005F_x003E_k__BackingField= OWBHelper.emptyGuid();
    
    public Integer _x005F_x003C_TipoComprovanteIdDefault_x005F_x003E_k__BackingField=0;
    
    public Boolean _x005F_x003C_Totem_x005F_x003E_k__BackingField=false;
    
    public String _x005F_x003C_VersaoClient_x005F_x003E_k__BackingField;

    public OWBPointOfSaleConfig ()
    {
    }

    public OWBPointOfSaleConfig (java.lang.Object paramObj,OWBExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("_x003C_CabecalhoComprovante_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_CabecalhoComprovante_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_CabecalhoComprovante_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ClientTefId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ClientTefId_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_ClientTefId_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ColetarLogs_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ColetarLogs_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_ColetarLogs_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_EmpresasContasSemFatura_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_EmpresasContasSemFatura_x005F_x003E_k__BackingField = OWBEnums.EmpresasContaSemFatura.getStatusFlags(j.toString());
                        }
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Estado_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Estado_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_Estado_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ExibirBotaoFechar_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ExibirBotaoFechar_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_ExibirBotaoFechar_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_FormatoData_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_FormatoData_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_FormatoData_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ImportarArquivos_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ImportarArquivos_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_ImportarArquivos_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_IpClient_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_IpClient_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_IpClient_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_LastOnlineNotification_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_LastOnlineNotification_x005F_x003E_k__BackingField = OWBHelper.ConvertFromWebService(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof java.util.Date){
                        this._x005F_x003C_LastOnlineNotification_x005F_x003E_k__BackingField = (java.util.Date)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_LimparLogs_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_LimparLogs_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_LimparLogs_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_LogDetalhado_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_LogDetalhado_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_LogDetalhado_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_LogoClienteContentType_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_LogoClienteContentType_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_LogoClienteContentType_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_LogoCliente_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_LogoCliente_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null){
                        this._x005F_x003C_LogoCliente_x005F_x003E_k__BackingField = obj.toString();
                    }
                    continue;
                }
                if (info.name.equals("_x003C_MaxNotificationInterval_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_MaxNotificationInterval_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_MaxNotificationInterval_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_MensagemCabecalho_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_MensagemCabecalho_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_MensagemCabecalho_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_MensagemIndisponivel_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_MensagemIndisponivel_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_MensagemIndisponivel_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Modulos_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Modulos_x005F_x003E_k__BackingField = OWBEnums.ModulosPDV.getStatusFlags(j.toString());
                        }
                    }
                    continue;
                }
                if (info.name.equals("_x003C_MultipagosPath_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_MultipagosPath_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_MultipagosPath_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Nome_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Nome_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_Nome_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_NotificationInterval_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_NotificationInterval_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_NotificationInterval_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_PointOfSaleID_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_PointOfSaleID_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_PointOfSaleID_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_PointOfSaleIdParceiro_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_PointOfSaleIdParceiro_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_PointOfSaleIdParceiro_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ReiniciarPrograma_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ReiniciarPrograma_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_ReiniciarPrograma_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_RodapeComprovante_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_RodapeComprovante_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_RodapeComprovante_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_StatusServicoPDV_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_StatusServicoPDV_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_StatusServicoPDV_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_TefRequestPath_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_TefRequestPath_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_TefRequestPath_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_TefResponsePath_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_TefResponsePath_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_TefResponsePath_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_TerminalId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_TerminalId_x005F_x003E_k__BackingField = UUID.fromString(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof UUID){
                        this._x005F_x003C_TerminalId_x005F_x003E_k__BackingField = (UUID)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_TipoComprovanteIdDefault_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_TipoComprovanteIdDefault_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_TipoComprovanteIdDefault_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Totem_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Totem_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_Totem_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_VersaoClient_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_VersaoClient_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_VersaoClient_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this._x005F_x003C_CabecalhoComprovante_x005F_x003E_k__BackingField!=null?this._x005F_x003C_CabecalhoComprovante_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==1)
        {
            return _x005F_x003C_ClientTefId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==2)
        {
            return _x005F_x003C_ColetarLogs_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==3)
        {
            return OWBEnums.EmpresasContaSemFatura.getFlagValue(_x005F_x003C_EmpresasContasSemFatura_x005F_x003E_k__BackingField);
        }
        if(propertyIndex==4)
        {
            return this._x005F_x003C_Estado_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Estado_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==5)
        {
            return _x005F_x003C_ExibirBotaoFechar_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==6)
        {
            return this._x005F_x003C_FormatoData_x005F_x003E_k__BackingField!=null?this._x005F_x003C_FormatoData_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==7)
        {
            return _x005F_x003C_ImportarArquivos_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==8)
        {
            return this._x005F_x003C_IpClient_x005F_x003E_k__BackingField!=null?this._x005F_x003C_IpClient_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==9)
        {
            return this._x005F_x003C_LastOnlineNotification_x005F_x003E_k__BackingField!=null?OWBHelper.getDateTimeFormat().format(this._x005F_x003C_LastOnlineNotification_x005F_x003E_k__BackingField):SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==10)
        {
            return _x005F_x003C_LimparLogs_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==11)
        {
            return _x005F_x003C_LogDetalhado_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==12)
        {
            return this._x005F_x003C_LogoClienteContentType_x005F_x003E_k__BackingField!=null?this._x005F_x003C_LogoClienteContentType_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==13)
        {
            return this._x005F_x003C_LogoCliente_x005F_x003E_k__BackingField!=null?this._x005F_x003C_LogoCliente_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==14)
        {
            return _x005F_x003C_MaxNotificationInterval_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==15)
        {
            return this._x005F_x003C_MensagemCabecalho_x005F_x003E_k__BackingField!=null?this._x005F_x003C_MensagemCabecalho_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==16)
        {
            return this._x005F_x003C_MensagemIndisponivel_x005F_x003E_k__BackingField!=null?this._x005F_x003C_MensagemIndisponivel_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==17)
        {
            return OWBEnums.ModulosPDV.getFlagValue(_x005F_x003C_Modulos_x005F_x003E_k__BackingField);
        }
        if(propertyIndex==18)
        {
            return this._x005F_x003C_MultipagosPath_x005F_x003E_k__BackingField!=null?this._x005F_x003C_MultipagosPath_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==19)
        {
            return this._x005F_x003C_Nome_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Nome_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==20)
        {
            return _x005F_x003C_NotificationInterval_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==21)
        {
            return _x005F_x003C_PointOfSaleID_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==22)
        {
            return this._x005F_x003C_PointOfSaleIdParceiro_x005F_x003E_k__BackingField!=null?this._x005F_x003C_PointOfSaleIdParceiro_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==23)
        {
            return _x005F_x003C_ReiniciarPrograma_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==24)
        {
            return this._x005F_x003C_RodapeComprovante_x005F_x003E_k__BackingField!=null?this._x005F_x003C_RodapeComprovante_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==25)
        {
            return _x005F_x003C_StatusServicoPDV_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==26)
        {
            return this._x005F_x003C_TefRequestPath_x005F_x003E_k__BackingField!=null?this._x005F_x003C_TefRequestPath_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==27)
        {
            return this._x005F_x003C_TefResponsePath_x005F_x003E_k__BackingField!=null?this._x005F_x003C_TefResponsePath_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==28)
        {
            return _x005F_x003C_TerminalId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==29)
        {
            return _x005F_x003C_TipoComprovanteIdDefault_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==30)
        {
            return _x005F_x003C_Totem_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==31)
        {
            return this._x005F_x003C_VersaoClient_x005F_x003E_k__BackingField!=null?this._x005F_x003C_VersaoClient_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 32;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_CabecalhoComprovante_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_ClientTefId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_ColetarLogs_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_EmpresasContasSemFatura_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Estado_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_ExibirBotaoFechar_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_FormatoData_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_ImportarArquivos_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_IpClient_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_LastOnlineNotification_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_LimparLogs_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_LogDetalhado_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_LogoClienteContentType_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_LogoCliente_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_MaxNotificationInterval_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_MensagemCabecalho_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_MensagemIndisponivel_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Modulos_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_MultipagosPath_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Nome_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_NotificationInterval_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_PointOfSaleID_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_PointOfSaleIdParceiro_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_ReiniciarPrograma_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_RodapeComprovante_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_StatusServicoPDV_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_TefRequestPath_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_TefResponsePath_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_TerminalId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_TipoComprovanteIdDefault_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==30)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_Totem_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
        if(propertyIndex==31)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_VersaoClient_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
