package net.multicom.WSTestes;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 08-12-2015
//
//---------------------------------------------------


import net.multicom.WSTestes.OWBExtendedSoapSerializationEnvelope;

import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.math.BigDecimal;
import java.util.Hashtable;

public abstract class OWBProduto extends AttributeContainer implements KvmSerializable
{

    
    public String _x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField;
    
    public String _x005F_x003C_Codigo_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_ModeloId_x005F_x003E_k__BackingField=0;
    
    public String _x005F_x003C_Nome_x005F_x003E_k__BackingField;
    
    public net.multicom.WSTestes.OWBOperadora _x005F_x003C_Operadora_x005F_x003E_k__BackingField;
    
    public Integer _x005F_x003C_ValidadeCreditos_x005F_x003E_k__BackingField=0;
    
    public BigDecimal _x005F_x003C_ValorCompra_x005F_x003E_k__BackingField=BigDecimal.ZERO;
    
    public BigDecimal _x005F_x003C_ValorIncremento_x005F_x003E_k__BackingField=BigDecimal.ZERO;
    
    public BigDecimal _x005F_x003C_ValorMaximo_x005F_x003E_k__BackingField=BigDecimal.ZERO;
    
    public BigDecimal _x005F_x003C_ValorMinimo_x005F_x003E_k__BackingField=BigDecimal.ZERO;
    
    public Boolean _x005F_x003C_ValorVariavel_x005F_x003E_k__BackingField=false;
    
    public BigDecimal _x005F_x003C_ValorVenda_x005F_x003E_k__BackingField=BigDecimal.ZERO;

    public OWBProduto ()
    {
    }

    public OWBProduto (java.lang.Object paramObj,OWBExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("_x003C_CodigoOperadora_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Codigo_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Codigo_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_Codigo_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ModeloId_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ModeloId_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_ModeloId_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Nome_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_Nome_x005F_x003E_k__BackingField = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._x005F_x003C_Nome_x005F_x003E_k__BackingField = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_Operadora_x003E_k__BackingField"))
                {
                    java.lang.Object j = obj;
                    this._x005F_x003C_Operadora_x005F_x003E_k__BackingField = (net.multicom.WSTestes.OWBOperadora)__envelope.get(j, net.multicom.WSTestes.OWBOperadora.class);
                    continue;
                }
                if (info.name.equals("_x003C_ValidadeCreditos_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ValidadeCreditos_x005F_x003E_k__BackingField = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this._x005F_x003C_ValidadeCreditos_x005F_x003E_k__BackingField = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ValorCompra_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ValorCompra_x005F_x003E_k__BackingField = new BigDecimal(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof BigDecimal){
                        this._x005F_x003C_ValorCompra_x005F_x003E_k__BackingField = (BigDecimal)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ValorIncremento_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ValorIncremento_x005F_x003E_k__BackingField = new BigDecimal(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof BigDecimal){
                        this._x005F_x003C_ValorIncremento_x005F_x003E_k__BackingField = (BigDecimal)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ValorMaximo_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ValorMaximo_x005F_x003E_k__BackingField = new BigDecimal(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof BigDecimal){
                        this._x005F_x003C_ValorMaximo_x005F_x003E_k__BackingField = (BigDecimal)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ValorMinimo_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ValorMinimo_x005F_x003E_k__BackingField = new BigDecimal(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof BigDecimal){
                        this._x005F_x003C_ValorMinimo_x005F_x003E_k__BackingField = (BigDecimal)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ValorVariavel_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ValorVariavel_x005F_x003E_k__BackingField = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this._x005F_x003C_ValorVariavel_x005F_x003E_k__BackingField = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("_x003C_ValorVenda_x003E_k__BackingField"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._x005F_x003C_ValorVenda_x005F_x003E_k__BackingField = new BigDecimal(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof BigDecimal){
                        this._x005F_x003C_ValorVenda_x005F_x003E_k__BackingField = (BigDecimal)obj;
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this._x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField!=null?this._x005F_x003C_CodigoOperadora_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==1)
        {
            return this._x005F_x003C_Codigo_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Codigo_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==2)
        {
            return _x005F_x003C_ModeloId_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==3)
        {
            return this._x005F_x003C_Nome_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Nome_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==4)
        {
            return this._x005F_x003C_Operadora_x005F_x003E_k__BackingField!=null?this._x005F_x003C_Operadora_x005F_x003E_k__BackingField:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==5)
        {
            return _x005F_x003C_ValidadeCreditos_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==6)
        {
            return this._x005F_x003C_ValorCompra_x005F_x003E_k__BackingField!=null?this._x005F_x003C_ValorCompra_x005F_x003E_k__BackingField.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this._x005F_x003C_ValorIncremento_x005F_x003E_k__BackingField!=null?this._x005F_x003C_ValorIncremento_x005F_x003E_k__BackingField.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this._x005F_x003C_ValorMaximo_x005F_x003E_k__BackingField!=null?this._x005F_x003C_ValorMaximo_x005F_x003E_k__BackingField.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this._x005F_x003C_ValorMinimo_x005F_x003E_k__BackingField!=null?this._x005F_x003C_ValorMinimo_x005F_x003E_k__BackingField.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return _x005F_x003C_ValorVariavel_x005F_x003E_k__BackingField;
        }
        if(propertyIndex==11)
        {
            return this._x005F_x003C_ValorVenda_x005F_x003E_k__BackingField!=null?this._x005F_x003C_ValorVenda_x005F_x003E_k__BackingField.toString():SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_CodigoOperadora_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Codigo_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_ModeloId_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_Nome_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==4)
        {
            info.type = net.multicom.WSTestes.OWBOperadora.class;
            info.name = "_x003C_Operadora_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "_x003C_ValidadeCreditos_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_ValorCompra_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_ValorIncremento_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_ValorMaximo_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_ValorMinimo_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "_x003C_ValorVariavel_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "_x003C_ValorVenda_x003E_k__BackingField";
            info.namespace= "http://schemas.datacontract.org/2004/07/MulticomNet.MultiPagos.Domain.Recarga";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
